//%GenSrc:1:ddYpvG17OUuq6SAX3ub1zQ
/*
 * This code was generated by InstinctAI.
 *
 * It is safe to edit this file.
 */

namespace instinctai.usr.behaviours
{
    using UnityEngine;
    using com.kupio.instinctai;
    using System.Collections.Generic;

    public partial class ParentBehavior : MonoBehaviour
    {

        public GameObject myChildObject;
        public GameObject myChildBuffer;
        public Agent myChildScript;

        public bool following;
        public bool DontMove;

        public Vector2 pos;
        public Vector2 velocity;
        public Vector2 target;
        public float speed;

        public BoxCollider2D bc;
        public Rigidbody2D rb;

        public float Money;

        private void Awake()
        {
            GetComponents();
            GetMyChild();
        }

        public void FixedUpdate()
        {
            Vector2MyPos();
            if(following)
            {
                SetTarget(myChildScript.pos);
            }
            if (!DontMove)
            {
                VelocitySet();
                MoveToTarget();
            }
        }

        public void GetComponents()
        {
            bc = GetComponent<BoxCollider2D>();
            rb = GetComponent<Rigidbody2D>();
        }

        public void GetMyChild()
        {
            myChildObject = transform.GetChild(0).gameObject;
            myChildScript = GetComponentInChildren<Agent>();
            Debug.Log("Got My Child");
            myChildScript.GetMyParent();
        }

        public void Vector2MyPos()
        {
            pos = new Vector2(transform.position.x, transform.position.y);
        }

        public void VelocitySet()
        {
            Vector2 tempVel = target - pos;
            tempVel.Normalize();
            tempVel *= speed;
            velocity = tempVel;
        }

        public void MoveToTarget()
        {
            rb.MovePosition((Vector2)transform.position + velocity);
        }

        public void SetTarget(Vector2 targetPos)
        {
            target = targetPos;
        }

        void OnTriggerEnter2D(Collider2D col)
        {
            if(col.gameObject == myChildBuffer)
            {
                DontMove = true;
            }
        }

        void OnTriggerExit2D(Collider2D col)
        {
            if (col.gameObject == myChildBuffer)
            {
                DontMove = false;
            }
        }


    }
}
